### ISSUE TITLE
Weird output from begiak's email module

### ISSUE THREAD

**Issue by svineet** [goavki/phenny#155] opened 2015-12-13 14:41 UTC
begiak
apertium-contact: Kevin Brubeck Unhammer un...@mm....st: Re: [Apertium-contact] =?utf-8?q?Apertium_har_sluttet_=C3=A5_virke_p?= =?utf-8?q?=C3=A5_PC=27en_min!?= 
apertium-contact: Kevin Brubeck Unhammer un...@mm....st: Re: =?utf-8?q?oversettelse_g=C3=A5r_ikke?=

maybe begiak should ignore urls in emails and print the actual text?

**Comment by unhammer** [comment] 2015-12-14 10:22
they're not urls, that's email encoding of unicode stuff (e.g. å turns into =C3=A5)

**Comment by shardulc** [comment] 2017-12-24 00:50
Duplicate of #260.

**Closed by shardulc** 2017-12-24 00:50 UTC
Labels: bug, modules
